package br.com.brelzin.crudteste.modelo;

// Generated 20/09/2015 22:11:09 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

/**
 * Unidade generated by hbm2java
 */
@Entity
@Table(name = "unidade", catalog = "brelzindb_teste")
@JsonIgnoreProperties({ "hibernateLazyInitializer", "handler" })
@JsonInclude(Include.NON_NULL)
public class Unidade implements java.io.Serializable {

	private Integer id;
	private String nome;
	private Set<Pessoa> pessoas = new HashSet<Pessoa>(0);

	public Unidade() {
	}

	public Unidade(String nome) {
		this.nome = nome;
	}

	public Unidade(String nome, Set<Pessoa> pessoas) {
		this.nome = nome;
		this.pessoas = pessoas;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "nome", nullable = false, length = 15)
	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	@JsonIgnore
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "unidade")
	public Set<Pessoa> getPessoas() {
		return this.pessoas;
	}

	public void setPessoas(Set<Pessoa> pessoas) {
		this.pessoas = pessoas;
	}

}
